set_property CFGBVS VCCO [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]

#ADC data bus
set_property PACKAGE_PIN J14 [get_ports ADC_DATA[0]]
set_property IOSTANDARD LVCMOS33 [get_ports ADC_DATA[0]]
set_property PACKAGE_PIN L14 [get_ports ADC_DATA[1]]
set_property IOSTANDARD LVCMOS33 [get_ports ADC_DATA[1]]
set_property PACKAGE_PIN L13 [get_ports ADC_DATA[2]]
set_property IOSTANDARD LVCMOS33 [get_ports ADC_DATA[2]]
set_property PACKAGE_PIN M14 [get_ports ADC_DATA[3]]
set_property IOSTANDARD LVCMOS33 [get_ports ADC_DATA[3]]
set_property PACKAGE_PIN M13 [get_ports ADC_DATA[4]]
set_property IOSTANDARD LVCMOS33 [get_ports ADC_DATA[4]]
set_property PACKAGE_PIN N14 [get_ports ADC_DATA[5]]
set_property IOSTANDARD LVCMOS33 [get_ports ADC_DATA[5]]
set_property PACKAGE_PIN P13 [get_ports ADC_DATA[6]]
set_property IOSTANDARD LVCMOS33 [get_ports ADC_DATA[6]]
set_property PACKAGE_PIN P12 [get_ports ADC_DATA[7]]
set_property IOSTANDARD LVCMOS33 [get_ports ADC_DATA[7]]
set_property PACKAGE_PIN N11 [get_ports ADC_DATA[8]]
set_property IOSTANDARD LVCMOS33 [get_ports ADC_DATA[8]]
set_property PACKAGE_PIN P11 [get_ports ADC_DATA[9]]
set_property IOSTANDARD LVCMOS33 [get_ports ADC_DATA[9]]

#ADC other signals
set_property PACKAGE_PIN H11 [get_ports ADC_DCO]
set_property IOSTANDARD LVCMOS33 [get_ports ADC_DCO]
set_property PACKAGE_PIN M2 [get_ports ADC_MODE]
set_property IOSTANDARD LVCMOS33 [get_ports ADC_MODE]
set_property PACKAGE_PIN P2 [get_ports ADC_SCLK]
set_property IOSTANDARD LVCMOS33 [get_ports ADC_SCLK]
set_property PACKAGE_PIN N1 [get_ports ADC_SDIO]
set_property IOSTANDARD LVCMOS33 [get_ports ADC_SDIO]
set_property PACKAGE_PIN P3 [get_ports ADC_CS]
set_property IOSTANDARD LVCMOS33 [get_ports ADC_CS]

#debug / status 
set_property PACKAGE_PIN J13 [get_ports LED1]
set_property IOSTANDARD LVCMOS33 [get_ports LED1]
set_property PACKAGE_PIN J12 [get_ports LED2]
set_property IOSTANDARD LVCMOS33 [get_ports LED2]
set_property PACKAGE_PIN G14 [get_ports DEBUG_TX]
set_property IOSTANDARD LVCMOS33 [get_ports DEBUG_TX]
set_property PACKAGE_PIN H12 [get_ports DEBUG_RX]
set_property IOSTANDARD LVCMOS33 [get_ports DEBUG_RX]

#interface
set_property PACKAGE_PIN B1 [get_ports FIBER_TX]
set_property IOSTANDARD LVCMOS33 [get_ports FIBER_TX]
set_property PACKAGE_PIN C1 [get_ports FIBER_RX]
set_property IOSTANDARD LVCMOS33 [get_ports FIBER_RX]
set_property PACKAGE_PIN J2 [get_ports RS485D]
set_property IOSTANDARD LVCMOS33 [get_ports RS485D]
set_property PACKAGE_PIN L1 [get_ports RS485DE]
set_property IOSTANDARD LVCMOS33 [get_ports RS485DE]
set_property PACKAGE_PIN M1 [get_ports RS485R]
set_property IOSTANDARD LVCMOS33 [get_ports RS485R]
set_property PACKAGE_PIN L2 [get_ports RS485RE]
set_property IOSTANDARD LVCMOS33 [get_ports RS485RE]
set_property PACKAGE_PIN J1 [get_ports RELAY1]
set_property IOSTANDARD LVCMOS33 [get_ports RELAY1]
set_property PACKAGE_PIN H2 [get_ports RELAY2]
set_property IOSTANDARD LVCMOS33 [get_ports RELAY2]

#comparators 
set_property PACKAGE_PIN H13 [get_ports ULVO]
set_property IOSTANDARD LVCMOS33 [get_ports ULVO]
set_property PACKAGE_PIN K12 [get_ports ZCS]
set_property IOSTANDARD LVCMOS33 [get_ports ZCS]


#gate drive
set_property PACKAGE_PIN B14 [get_ports GATE1_P]
set_property IOSTANDARD LVCMOS33 [get_ports GATE1_P]
set_property PACKAGE_PIN D14 [get_ports GATE1_N]
set_property IOSTANDARD LVCMOS33 [get_ports GATE1_N]
set_property PACKAGE_PIN F14 [get_ports GATE2_P]
set_property IOSTANDARD LVCMOS33 [get_ports GATE2_P]
set_property PACKAGE_PIN H14 [get_ports GATE2_N]
set_property IOSTANDARD LVCMOS33 [get_ports GATE2_N]

#enable pullup on debug RX
set_property PULLUP TRUE [get_ports DEBUG_RX]